bridge:
  ros__parameters:
    ego_namespace: 'ego_racecar'
    ego_scan_topic: 'scan'
    ego_odom_topic: 'odom'
    ego_opp_odom_topic: 'opp_odom'
    ego_drive_topic: 'drive'
    opp_namespace: 'opp_racecar'
    opp_scan_topic: 'opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: 'opp_drive'

    scan_distance_to_base_link: 0.0

    scan_fov: 4.7
    scan_beams: 1080

    map_path: '/home/lizbeth/F1Tenth-Repository/src/f1tenth_gym_ros/maps/Budapest'
    map_img_ext: '.png'
    map_yaml_ext: '.yaml'

    num_agent: 1

    sx: 56.0848
    sy: 20.8874
    stheta: 1.30257

    sx1: 9.5
    sy1: 8.5
    stheta1: 3.14

    kb_teleop: True
